# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 文韬   #网站标题
subtitle: '始终如一'  #网站副标题
description: '本博客记录博主学习内容'   #网站描述
keywords:   #网站关键词
author: Wtli    #您的名字
language: zh-CN  #语言
timezone: ''      #时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wtlizzz.github.io    #网址
root: /     #网站根目录
permalink: :title/    #文章的 永久链接 格式 defaults: :year/:month/:day/:title/
permalink_defaults:   #永久链接中各部分的默认值
pretty_urls:    #改写 permalink 的值来美化 URL
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - .nojekyll
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#  type: ''
deploy:
  - type: git
    repo: https://github.com/wtlizzz/wtlizzz.github.io.git
    branch: master
    ignore_hidden: false

## hexo-admin authentification
#admin:
#  username: wtlizzz
#  password_hash: $2a$10$KO4GyTQER0ptYmDNJOjqSem4MLWBa8wmhev6bMUfRo1qrn8jff2s2
#  secret: my super secret phrase

#hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."


live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-wanko
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: false
  react:
    opacity: 0.7

    # Live2D
    ## https://github.com/EYHN/hexo-helper-live2d
    #live2d:
    #  enable: true
    #  # enable: false
    #  pluginRootPath: live2dw/ # Root path of plugin to be on the site (Relative)
    #  pluginJsPath: lib/ # JavaScript path related to plugin's root (Relative)
    #  pluginModelPath: assets/ # Relative model path related to plugin's root (Relative)
    #  scriptFrom: local # Default
    #  # scriptFrom: jsdelivr # jsdelivr CDN
    #  # scriptFrom: unpkg # unpkg CDN
    #  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # Your custom url
    #  tagMode: false # Whether only to replace live2d tag instead of inject to all pages
    #  log: false # Whether to show logs in console
    #  model:
    #    use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # folder name in (hexo base dir)/live2d_models/
    # use: ./wives/wanko # folder path relative to hexo base dir
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # Your custom url
